services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: # Set manually in Render after deployment
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host.render.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: attendance_db
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: # Set securely in Render dashboard
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
