services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan config:cache
      php artisan key:generate
      php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: # Set this manually in Render dashboard after first deploy
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host.render.com   # Update with actual MySQL host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: attendance_db
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: your-db-password
